<a href="https://colab.research.google.com/github/KumJungMin/TF_machine_learning/blob/master/hypothesis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 텐서플로우 사용법

## 1.1 텐서와 그래프 실행

In [5]:
#1. 텐서플로우를 사용하기 위해 텐서플로우 라이브러리 불러오기
import tensorflow as tf

#2. tf.constant('상수'), 상수를 hello 변수에 저장하는 코드
hello = tf.constant('Hello, Tensorflow')
print(hello)

tf.Tensor(b'Hello, Tensorflow', shape=(), dtype=string)


- 텐서플로우는 rank, shape라는 개념을 지닌다.

  : rank 란 특정 배열의 차원을 이야기

  : shape 이란 특정 배열이 어떻게 생겼는지, 즉 몇개의 요소가 있는지

  : d-type은 해당 텐서에 담긴 요소들의 자료형(string, float, int 등)

In [8]:
3                                           # rank:0->스칼라    | shape : []
[1.0 , 2.0, 3.]                             # rank:1->벡터      | shape : [3]
[[1.0 , 2.0, 3.], [1.0 , 2.0, 3.]]          # rank:2->행렬      | shape : [2,3]
[[[1.0 , 2.0, 3.0]],[[1.0 , 2.0, 3.]]]      # rank:3->3차원 텐서 | shape : [2,1,3] 

In [9]:
#텐서를 사용해, 다양한 연산 수행이 가능
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c) 

#tf.Tensor(42, shape=(), dtype=int32)
#tf.Tensor(결과값, shape=(), dtype=타입)

tf.Tensor(42, shape=(), dtype=int32)


- 텐서플로우는 그래프 생성, 실행이 주를 이룬다.

- 그러므로, 결과값의 경우 tf.Tensor()형태로 나온다. 

- 그래프는 텐서들의 연산 모음이다.

- 텐서 플로우는 텐서, 텐서의 연산을 먼저 정의하여 그래프를 만들고,
  연산을 실행하는 코드를 넣어 원하는 시점에 실제 연산을 수행한다.(자연실행 방식)


In [18]:
#그래프 실행 : Session 안에서 이루어짐(지원X)
# sess = tf.Session()
# print(sess.run(hello))
# print(sess.run([a,b,c]))
# sess.close()

#그래프 실행 : 일반 파이썬처럼 가능
 print((hello))      #tf.Tensor(b'Hello, Tensorflow', shape=(), dtype=string)
print(([a,b,c]))      #[10,32,42]
#[  <tf.Tensor: shape=(), dtype=int32, numpy=10>, 
#   <tf.Tensor: shape=(), dtype=int32, numpy=32>, 
#   <tf.Tensor: shape=(), dtype=int32, numpy=42>  ]

[<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=32>, <tf.Tensor: shape=(), dtype=int32, numpy=42>]


### Session이 없다고 뜬다면?

- TF v2.0은 v1.0의 그래프 모드에 대한 Eager 모드를 지원합니다. 

- 따라서 tf.session ()은 v2.0에서 지원되지 않습니다. 

- 따라서 Eager 모드에서 작동하도록 코드를 다시 작성하는 것이 좋습니다.

<br/>

### 이제는 일반 파이썬처럼 즉시 실행이 가능!  

텐서플로 1.x에서는 사용자가 tf.* API를 호출해서 추상 구문 트리를 수동으로 구성했습니다. 그다음 session.run()을 호출할 때 출력 텐서와 입력 텐서를 전달하여 추상 구문 트리를 수동으로 컴파일합니다. 텐서플로 2.0은 (보통의 파이썬처럼) 즉시 실행됩니다. 텐서플로 2.0에서 그래프와 세션은 구현 상세(implementation detail)처럼 느껴질 것입니다.

즉시 실행으로 인한 부수효과 중 하나는 더이상 tf.control_dependencies()이 필요하지 않다는 것입니다. 모든 코드는 라인 순서대로 실행됩니다(tf.function 안의 코드도 이 효과로 쓰여진 순서대로 실행됩니다).
<a href="https://www.tensorflow.org/guide/effective_tf2">공식문서 보기</a>


In [13]:
#TF1.x hello world :
# msg = tf.constant('Hello, TensorFlow!')
# sess = tf.Session()
# print(sess.run(msg))

#TF2.x hello world :
msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

Hello, TensorFlow!


## 1.2 플레이스홀더와 변수

- 플레이스홀더 : 그래프에 사용할 입력값을 나중에 받기 위해 사용하는 매개변수


- 변수 : 그래프를 최적화하는 용도, 학습 함수가 학습한 결과를 갱신하기 위해 쓰는 변수. <br/> 이 변수값에 따라 신경망의 성능이 좌우.

### placehoder는 새 버전에서는 지원하지 않습니다. 그러므로...
- 아래와 같이 v1을 사용하기 위해 v2를 꺼둡니다.
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x = tf.placeholder(shape=[None, 2], dtype=tf.float32)
```

- 하지만 다음과 같은 알림말이 뜰 겁니다. 개념 확인을 위해서만 v1을 쓰고 실제 코딩시 사용하지 않는 게 좋습니다.
" is deprecated and will be removed in a future version."

In [20]:
import tensorflow.compat.v1 as tf_1
tf_1.disable_v2_behavior()
x = tf_1.placeholder(shape=[None, 2], dtype=tf.float32)

# placeholder
X = tf_1.placeholder(tf.float32, [None, 3])
print(X)

#Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
#(?,3)모양의 float32 자료형을 가진 텐서가 생성

Instructions for updating:
non-resource variables are not supported in the long term
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)


- 나중에 placeholder X에 넣을 자료를 정의해봅시다.

- 앞서 텐서 모양은 (?,3)으로, 두 번째 차원은 요소를 3개씩 가지고 있어야 한다.

In [21]:
x_data = [[1,2,3], [4,5,6]]

In [24]:
#변수 정의
#v2(random.normal) - v1(random_normal)
#random.normal을 사용해, 정규분포의 무작위 값으로 초기화함
w = tf.Variable(tf.random.normal([3,2]))  #[3,2]행렬형태의 텐서 -> ex) [[0.1, 0.1], [0.2, 0.2], [0.3, 0.3]]
b= tf.Variable(tf.random.normal([2,1]))   #[2,1]행렬형태의 텐서

In [26]:
#입력값과 변수를 계산해보자
#w,x는 행렬이므로, tf.matmal함수를 사용
#행렬이 아닌경우 -> (*), tf.mul를 사용
expr = tf.matmul(X, w) + b

- 앞선, 두 행렬을 곱하기 위해서는 같아야 하는 게 있다. (AxB)

- X[0, a], B[a, 2]처럼 X의열 == B의 행이 같아야함

In [28]:
# 앞선 결과들을 실행해보자 v1방법
sess = tf_1.Session()

#앞에서 정의한 변수를 초기화
#기존학습값을 가져오는 게 아닌 새로운 값을 가져오는 것이므로 연산 전 이 함수 필수
sess.run(tf_1.global_variables_initializer()) 

print("=== x_data ===")
print(x_data)
print("=== w ===")
print(w)
print("=== b ===")
print(b)
print("=== expr ===")

#feed_dict()의 매개변수는, 그래프를 실행할 때 사용할 입력값으로 지정
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()



# === x_data ===
# [[1, 2, 3], [4, 5, 6]]
# === w ===
# <tf.Variable 'Variable_2:0' shape=(3, 2) dtype=float32>
# === b ===
# <tf.Variable 'Variable_3:0' shape=(2, 1) dtype=float32>
# === expr(행렬곱[2,3][3,2]+형렬 수식[2,1]) ===
# [[ 0.69783604 -2.5531518 ]
#  [ 1.4701934  -0.4009331 ]]

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== w ===
<tf.Variable 'Variable_2:0' shape=(3, 2) dtype=float32>
=== b ===
<tf.Variable 'Variable_3:0' shape=(2, 1) dtype=float32>
=== expr ===
[[ 0.69783604 -2.5531518 ]
 [ 1.4701934  -0.4009331 ]]


- expr수식에는 X,w,b를 사용했다.

- X는 placeholder라 X에 값을 넣지 않으면 오류가 생긴다. 

- 따라서 미리 정의한 x_data를 X값으로 넣어준다. {X : x_data}

## 1. 선형회귀모델 구현하기

- 선형회귀란, 주어진 x,y값을 가지고 서로 간의 관계를 파악하는 것이다.

- 이 관계를 알게되면 새로운 x가 주어졌을 때 y값을 쉽게 알 수 있다.

- 어떤 입력에 대한 출력을 예측하는 것, 이것이 머신러닝의 기초이다.

- 텐서플로의 최적화 함수를 이용해, x와 y의 상관관계를 분석하는 선형회귀모델을 실행해보자.

- 아래 코드는 주어진 x_data와 y_data의 상관관계를 파악하고자 한다.

In [29]:
#x,y의 상관관계를 설명하기 위한 변수인 W, b를 각각 -1.0~1.0사이의 균등분포를 가진 무작위 값으로 초기화한다.

W = tf.Variable(tf.random.uniform([1], -1.0, 1.0))   #uniform(shape, start, end)
b = tf.Variable(tf.random.uniform([1], -1.0, 1.0))

In [37]:
x_data = [1,2,3]
y_data = [1,2,3]

In [30]:
#자료를 입력받을 placeholder를 설정한다.
X = tf_1.placeholder(tf.float32, name="X")  #shape, name
Y = tf_1.placeholder(tf.float32, name="Y")

- x,y의 상관관계(선형관계)를 분석하기 위한 수식을 아래 코드에 작성한다.

- W와의 곱과 b의 합을 통해 -> X,Y의 관계를 설명한다는 말이다.

- X가 주어졌을 때 -> Y를 만들어 낼 수 있는 W, b를 찾아내겠다는 의미

- W, X는 행렬이 아니므로 tf.matmal이 아닌 기본 곱셈 연산자를 쓴다.

- 가중치(w)는 입력이 결과에 주는 영향을 조절하는 매개변수

- 편향(b)은 노드(x)가 얼마나 쉽게 활성화(1로 출력; activation)되느냐를 조정하는 매개변수

In [31]:
hypothsis = W*X + b     #W(가중치), b(편향)

### 손실함수

: 한 쌍(x,y)의 데이터에 대한 손실값을 계산하는 함수이다.

: 손실값은 실제값과 모델로 예측한 값이 얼마나 차이가 나는가를 나타내는 값이다.

<br/>

: 손실값이 작을수록 그 모델이 X,Y의 관계를 잘 설명하고 있다는 뜻이다.

: 손실값이 작을수록 주어진 X값에 대한 Y값을 정확하게 예측할 수 있다는 뜻이다.

: 이러한 손실을 전체데이터에 대해 구한 경우, 이를 비용이라고 한다.


<br/>

: 즉, 학습이란 변수들의 값을 다양하게 넣어 계산하면서 -> 이러한 손실을 최소화하는 W, b를 구하는 것

: 손실값으로, (예측값과 실제값의 거리)를 자주 사용

: 우리는 손실값을 (예측값-실제값)^2 하고, 비용은 모든 데이터에 대한 손실값의 평균으로 한다.

In [32]:
cost = tf.reduce_mean(tf.square(hypothsis - Y))

In [34]:
#경사하강법최적화함수를 이용해 -> 손실값을 최소하는 연산 그래프를 생성
optimizer = tf_1.train.GradientDescentOptimizer(learning_rate=0.1)  #v1 - GradientDescentOptimizer
train_op = optimizer.minimize(cost)

### 최적화 함수?

- 가중치와 편향 값을 변경해주면서, 손실값을 최소화하는 가장 최적화된 가중치와 편향값을 찾아주는 함수이다.

- 최적화를 빠르게 하기 위해 여러가지 방법을 사용하는데 경사하강법이 제일 기본적인 알고리즘이다

- 경사하강법은 함수의 기울기를 구하고 -> 기울기가 낮은 쪽으로 계속 이동하면서 -> 최적의 값을 찾아 나가는 것이다.

<br/>

- 최적화 함수의 학습률(learning_rate)는 학습을 얼마나 급하게 할 건지 설정하는 값이다.

- 학습률이 너무 크면, 최적의 손실값을 차지 못하고 지나치게 된다.

- 학습률이 너무 작으면, 학습 속도가 매우 느려진다.

- 이처럼, 학습을 하는 과정에 영향을 주는 변수를 "하이퍼파라미터"라고 한다.

<br/>

- 하이퍼파라미터값에 따라 학습 속도, 신경망 성능이 크게 달라진다.

- 머신러닝에서는 하이퍼파라미터를 잘 튜닝하는 게 큰 과제이다.


In [45]:
#변수 초기화
#With 기능을 사용해 세션 블록을 만들고 자동처리되게 한다.

with tf_1.Session() as sess:
  sess.run(tf_1.global_variables_initializer())


  #최적화를 수행하는 train_op 그래프 실행, 실행시마다 변화하는 손실값을 출력하게 함
  #학습을 100번 수행하며, feed_dict매개변수를 통해 -> 상관관계를 알아내고자 하는 x_data, y_data를 입력
  for step in range(100):
    _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
    print(step, cost_val, sess.run(W), sess.run(b))

  
  #실행해보기
  print("X:5 Y:", sess.run(hypothsis,feed_dict={X:5}))    #x가 5일때 -> y예측값
  print("X:2.5, Y", sess.run(hypothsis,feed_dict={X:2.5}))#x가 2.5일때 -> y예측값

  # X:5 Y: [4.9159107]  
  # X:2.5, Y [2.493007]

0 15.555412 [0.8240467] [0.85319895]
1 0.27193367 [0.6469902] [0.7529405]
2 0.08527886 [0.6752898] [0.7435563]
3 0.07915274 [0.68093014] [0.7247291]
4 0.0753681 [0.68883705] [0.7074112]
5 0.071787775 [0.69629127] [0.69039416]
6 0.068377785 [0.70359504] [0.6737988]
7 0.06512982 [0.7107202] [0.657601]
8 0.062036086 [0.71767426] [0.6417927]
9 0.059089333 [0.7244612] [0.62636447]
10 0.05628252 [0.73108494] [0.6113071]
11 0.05360904 [0.7375495] [0.5966117]
12 0.051062595 [0.74385864] [0.58226955]
13 0.048637077 [0.75001603] [0.5682722]
14 0.046326797 [0.75602555] [0.5546113]
15 0.044126213 [0.7618905] [0.54127884]
16 0.04203018 [0.7676145] [0.5282669]
17 0.04003373 [0.77320087] [0.5155677]
18 0.03813211 [0.77865297] [0.5031738]
19 0.036320787 [0.783974] [0.49107787]
20 0.034595523 [0.7891671] [0.4792727]
21 0.032952238 [0.7942354] [0.46775132]
22 0.03138699 [0.7991818] [0.4565069]
23 0.029896071 [0.8040094] [0.4455328]
24 0.028476005 [0.8087208] [0.43482247]
25 0.027123341 [0.813319] [0.424